services:
  food-hunting-bot:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - --no-cache
    restart: always
    env_file:
      - .env
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /:/rootfs:ro
    environment:
      - ALLOW_INSECURE=true
networks:
  selenium-grid:
