# list of instagram club's website that potentially have free food
insta_links = {'unicef': 'https://www.instagram.com/usf_unicef/',
               'arabsatusf': 'https://www.instagram.com/arabsatusf/',
               'bootsusf': 'https://www.instagram.com/boostusf/',
               'bridgesinternational': 'https://www.instagram.com/usfbridgesinternational',
               'usf_casa': 'https://www.instagram.com/usf_casa/',
               'intousf': 'https://www.instagram.com/intousf/',
               'usf.hsc': 'https://www.instagram.com/usf.hsc/',
               'boricuas_usf': 'https://www.instagram.com/boricuas_usf/,',
               'acdusf': 'https://instagram.com/acdusf/',
               'isaatusf': 'https://www.instagram.com/isaatusf/',
               'usf.asa': 'https://www.instagram.com/usf.asa/',
               'nesa.usf': 'https://www.instagram.com/nesa.usf/',
               'belsausf': 'https://www.instagram.com/belsausf/',
               'lsa_usf': 'https://www.instagram.com/lsa_usf/',
               'eso_usf': 'https://www.instagram.com/eso_usf/',
               'pdtampa': 'https://www.instagram.com/pdtampa/',
               'sos_usf': 'https://www.instagram.com/sos_usf/',
               'usf_nihongobu': 'https://www.instagram.com/usf_nihongobu/',
               'usf_je': 'https://www.instagram.com/usf_je/',
               'usf_tsa': 'https://www.instagram.com/usf_tsa/',
               'censa_usf': 'https://www.instagram.com/censa_usf/',
               'usf_hillel': 'https://www.instagram.com/usf_hillel/',
               'visa.usf': 'https://www.instagram.com/visa.usf/',
               'colsausf': 'https://www.instagram.com/colsausf/',
               'usf_bullsformoffitt': 'https://www.instagram.com/usf_bullsformoffitt/',
               'hexaconsulting': 'https://www.instagram.com/hexaconsulting/',
               'iiseusf': 'https://www.instagram.com/iiseusf/',
               'usffoi': 'https://www.instagram.com/usffoi/',
               'usf.mbsm': 'https://www.instagram.com/usf.mbsm/',
               'usfaiche': 'https://www.instagram.com/usfaiche/',
               'kwusfclub': 'https://www.instagram.com/kwusfclub/',
               'uzsc.usf': 'https://www.instagram.com/uzsc.usf/',
               'tmcusf': 'https://www.instagram.com/tmcusf/',
               'bsa.usf': 'https://www.instagram.com/bsa.usf/',
               'usfswe': 'https://www.instagram.com/usfswe/',
               'uzswe': 'https://www.instagram.com/ssausf/',
               'fes.usf': 'https://www.instagram.com/fes.usf/',
               'kasausf': 'https://www.instagram.com/kasausf/',
               'usf_lasa': 'https://www.instagram.com/usf_lasa/',
               'usfdasa': 'https://www.instagram.com/usfdasa/',
               'apex.usf': 'https://www.instagram.com/apex.usf/',
               'sbo.usf': 'https://www.instagram.com/sbo.usf/',
               'hsu_usf': 'https://www.instagram.com/hsu_usf/',
               'usfrealestatesociety': 'https://www.instagram.com/usfrealestatesociety/',
               'datascienceusf': 'https://www.instagram.com/datascienceusf/',
               'cclc_at_usf': 'https://www.instagram.com/cclc_at_usf/',
               'usfmasa': 'https://www.instagram.com/usfmasa/',
               'afsatusf': 'https://www.instagram.com/afsatusf/',
               'usfhosa': 'https://www.instagram.com/usfhosa/',
               'aedusf': 'https://www.instagram.com/aedusf/',
               'investmentclubatusf': 'https://www.instagram.com/investmentclubatusf/',
               'jamatusf': 'https://www.instagram.com/jamatusf/',
               'usfclubcreole': 'https://www.instagram.com/usfclubcreole/',
               'usfsase': 'https://www.instagram.com/usfsase/',
               'asia.usf': 'https://www.instagram.com/asia.usf/',
               'guysa.usf': 'https://www.instagram.com/guysa.usf/',
               'usfjcc': 'https://www.instagram.com/usfjcc/',
               'usfpsa': 'https://www.instagram.com/usfpsa/',
               'asa_usf': 'https://www.instagram.com/asa_usf/',
               'vsaatusf': 'https://www.instagram.com/vsaatusf/',
               'nazshalal': 'https://www.instagram.com/nazshalal/',
               'usfworld_issc': 'https://www.instagram.com/usfworld_issc/',
               'sia.usf': 'https://www.instagram.com/sia.usf/',
               'shpeusf': 'https://www.instagram.com/shpeusf/',
               'cceatusf': 'https://www.instagram.com/cceatusf/',
               'brasaatusf': 'https://www.instagram.com/brasaatusf/',
               'usfbsu': 'https://www.instagram.com/usfbsu/',
               'usfstudentgov_': 'https://www.instagram.com/usfstudentgov_/',
               'usfhonors': 'https://www.instagram.com/usfhonors/'}


def clubs_list():  # put the keys of insta_links dictionary into a list for the purpose of indexing
    clubs_list = []
    for i, (k, v) in enumerate(insta_links.items()):
        clubs_list.append(k)
    return clubs_list


def link(index, clubs_list):  # get link from specific club's name using indexing
    link = insta_links[clubs_list[index]]
    return link
